### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by tkornuta-nvidia** [chuangg/CLEVRER#3]
Want to use the CLEVRER dataset for research, but not sure what the license is? Can you please upload the license file/set project license file on github?

Thanks,
Tomasz

**Comment by chuangg** [comment]
Our dataset is under the CC0.

**Comment by tkornuta-nvidia** [comment]
Ok, thank you for the reply. Can you please merge the PR with license:
https://github.com/chuangg/CLEVRER/pull/4

Thanks.
